### ISSUE TITLE
Chapitre sur les Vec, slice, String, &str

### ISSUE THREAD

**Issue by GuillaumeGomez** [GuillaumeGomez/tuto-rust-fr#14]
Plusieurs personnes m'ont fait la demande d'un tel chapitre.

> **low**: **imperio**: un truc sur les Vec, Path, PathBuf, String, &str ce serait peut-être pas mal, non ?
> ...
> **Levans**: une slice, c'est une référence vers un morceau d'un array (une tranche, pour traduire littéralement)
> **Levans**: en gros, c'est un pointeur intelligent vers un premier élément associé à une taille

**Comment by lwandrebeck** [comment]
Quelques mots sur Box seraient aussi les bienvenus :)

**Comment by GuillaumeGomez** [comment]
Ça fait partie des nombreux sujets qu'il me faut encore écrire.
