### ISSUE TITLE
Proposition d'amélioration d'un exemple de boucle for

### ISSUE THREAD

**Issue by ciola** [GuillaumeGomez/tuto-rust-fr#153]
Bonjour,
Dans l'exemple des boucles for, changer l'exemple par :
for (i, j) in (6..10).enumerate() {
    println!("i = {} et j = {}", i, j);
}
Pour que personne ne pense que les j suivent les i.

**Comment by ciola** [comment]
À part les noms explicites donnés aux variables i et j, il me semble que l'exemple est toujours sur (5..10) et non sur (6..10) afin que les valeurs  ne se suivent pas.

**Comment by GuillaumeGomez** [comment]
Oh en effet, j'avais zappé le point principal, désolé. Je fix ça.

**Comment by GuillaumeGomez** [comment]
Corrigé dans https://github.com/GuillaumeGomez/tuto-rust-fr/pull/156.
