### ISSUE TITLE
Amélioration des run

### ISSUE THREAD

**Issue by ciola** [GuillaumeGomez/tuto-rust-fr#155]
Bonjour,
Il serait mieux que les boutons run qui permettent de tester le code ouvrent un nouvel onglet.
En effet, une fois sur play.rust-lang.org, quand on fait différents essais, il faut cliquer plusieurs fois sur le bouton de retour à la page précédente, alors qu'avec un nouvel onglet, il suffirait de fermer cet onglet.
D'avance merci.
Ciola

PS : Je suis débutant en rust et je ne sais pas si je dois poster une issue à chaque fois que je vois quelque chose à améliorer.
Existe-t-il une autre procédure?
D'avance merci.

**Comment by GuillaumeGomez** [comment]
Une issue pour chaque problème est très bien. Si jamais tu te sens assez à l'aise, n'hésite pas à faire une pull request directement (même si pour cette issue c'est du code "back" donc rien qui puisse être fait par quelqu'un d'autre que moi).

**Comment by GuillaumeGomez** [comment]
Voilà qui est corrigé, merci !
