### ISSUE TITLE
Référence à d'autres langage de programmation

### ISSUE THREAD

**Issue by ciola** [GuillaumeGomez/tuto-rust-fr#157]
Bonjour,
Je trouve que pour un livre qui s'Adresse aux débutants, il serait bon d'expliquer tous les concepts sans faire appel à d'autres langages.
Ex. "Sachez cependant que les types [isize](https://doc.rust-lang.org/stable/std/primitive.isize.html) et [usize](https://doc.rust-lang.org/stable/std/primitive.usize.html) existent aussi et sont l'équivalent de intptr_t et de uintptr_t en C/C++. En gros, sur un système 32 bits, ils feront respectivement 32 bits tandis qu'ils feront 64 bits sur un système 64 bits."

**Comment by GuillaumeGomez** [comment]
Il ne s'adresse pas aux débutants comme indiqué dans le premier chapitre :

> Pour suivre ce tutoriel, il est recommandé d'avoir déjà développé dans au moins un autre langage (C, C++, Java, JavaScript, Python, etc.). Ce n'est pas parce que Rust est un langage particulièrement difficile à apprendre, mais plutôt parce que les concepts abordés dans ce livre supposent une certaine familiarité avec la programmation. En d'autres termes, si vous êtes totalement novice en programmation, vous pouvez trouver certains passages de ce livre difficiles à suivre. Cela vous permettra notamment de vous concentrer sur les aspects spécifiques de Rust plutôt que de devoir assimiler à la fois les notions de base de la programmation et de Rust.
