### ISSUE TITLE
Explication insuffisante

### ISSUE THREAD

**Issue by ciola** [GuillaumeGomez/tuto-rust-fr#160]
Bonjour,
Je ne comprends pas les explications. Il faudrait rentrer un peu plus dans les exeplications du binder.
-------------------------------------- extrait --------------------------------------
Pratique ! Vous pouvez aussi "binder" (ou matcher sur un ensemble de valeurs) la variable avec le symbole "@" :
```
let i = 0i32;

match i {
    x @ 10..=100 => println!("{} est entre 10 et 100 (inclus)", x),
    x => println!("{} n'est pas entre 10 et 100 (inclus)", x)
};
```

**Comment by GuillaumeGomez** [comment]
Qu'est-ce qui coince du coup ? Savoir ce qui n'est pas compris m'aidera pour l'amélioration.

**Comment by GuillaumeGomez** [comment]
J'ai fait #164. Si jamais ce n'est pas suffisant, des explications supplémentaires sur comment je pourrais améliorer cette partie (ou plutôt ce qui est confus) serait le bienvenu. :)
