### ISSUE TITLE
small bug in Rust/1/5

### ISSUE THREAD

**Issue by fr001** [GuillaumeGomez/tuto-rust-fr#19]
##### Hello, nice tutorial, bravo 
````rust
let age : i32 = 17;
match age {
    tmp if tmp > 17 {
        println!("majeur !");
    }
    _ => {
        println!("mineur !");
    }
};
````
##### missing "=>" after 17
````rust
  match age {
    tmp if tmp > 17 => { println!("majeur !") }
                  _ => { println!("mineur !") }
  };  // semicolon for EOstt-block "match"
````
##### so I prefer this kind of layout, looks clearer to me, enlighten semicolon use,.. 
````rust
fn main() {
  let my_string = "hello";
  match my_string {                       // this layout is clearer
    "bonjour" => { println!("francais") } // NO EOstt semicolon before }
    "ciao" =>    { println!("italien")  } // NO EOstt semicolon before }
    "hello" =>   { println!("anglais")  } // NO EOstt semicolon before }
    "hola" =>    { println!("espagnol") } // NO EOstt semicolon before }
    _ =>         { println!("unknown language") } // NO EOstt semicolon before }
    // _ means "any other expression", kind of "else", not for next boolean
  };  // semicolon for EOstt-block "match"
}
````
##### Perhaps could you signal this nice rustc option (Compiler)
rustc hello.rs
from the Windows cmd shell 
outputs hello.exe **2.5Mega**  but  **50K** using the **-C prefer-dynamic** option 
````cmd 
   rustc hello.rs                    REM outputs hello.exe to launch
   hello                             REM launch, it displays: Hello World!
   rustc hello.rs -o hi              REM -output it as hi.exe  
   rustc -C prefer-dynamic hello.rs  REM reduce the output size dramatically !
   REM this dynamic option requires the availability at runtime of the Rust libraries.
   REM the PATH to Rust is updated if you choosed the option when installing it
````
##### perhaps a button to COPY or SEND code to https://play.rust-lang.org 
**To do these exercises**  in https://github.com/carols10cents/rustlings
    Thanks to btbytes' prlinks, you can now click on the links below to load the exercises in the rust playground!
##### Have a nice day
Francis, Brussel

**Comment by GuillaumeGomez** [comment]
Oh thanks ! And I was thinking about adding such a button (still working on the design ^^'). Why not directly open a PR for all these changes ?

Ah au fait, tu peux parler français si tu préfères (je suis français après tout !).

**Comment by GuillaumeGomez** [comment]
I added a "Run" button wich redirects to play.rust-lang.org with the block code.
I fixed the example (thanks again for that !).
I added your example (thanks for this too ^^).

Feel free to contribute any time !
