### ISSUE TITLE
Précisions sur les structures "newtype"

### ISSUE THREAD

**Issue by flobsx** [GuillaumeGomez/tuto-rust-fr#191]
Bonjour,

les structures "newtype" sont évoquées [dans 1_10.md](https://github.com/GuillaumeGomez/tuto-rust-fr/blob/master/src/1_10.md), mais sans explication.

Un paragraphe permettant de comprendre ce que c'est ou à quoi ca sert pourrait être intéressant.

Est-ce qu'il s'agit de la même chose qui est décrite dans le lien : https://rust-unofficial.github.io/patterns/patterns/behavioural/newtype.html ?

**Comment by GuillaumeGomez** [comment]
Préciser pour chaque type de structure serait bien en effet. Je vais ajouter ça.

**Comment by GuillaumeGomez** [comment]
C'est mis à jour.
