### ISSUE TITLE
Structure unitaire

### ISSUE THREAD

**Issue by tytouf** [GuillaumeGomez/tuto-rust-fr#2]
Dans la descriptions des structures, la structure unitaire "Comment peut-on utiliser une structure sans savoir ce qu'elle contient ? o_O". On appelle ce genre de structure des structures opaques. Cf http://en.wikipedia.org/wiki/Opaque_data_type

**Comment by GuillaumeGomez** [comment]
Le rustbook faisait mention d'une structure unitaire, j'ai juste traduit littéralement. Merci pour l'info. Tu crées une PR pour corriger ça ? (Comme c'est toi qui as trouvé l'erreur, ça me semble plus logique).

**Comment by GuillaumeGomez** [comment]
[Résolu](https://github.com/GuillaumeGomez/tuto-rust-fr/commit/92093e180a2ab18b4f166b90159f81dfb2398066).
