### ISSUE TITLE
Ajouter correspondances mots-clés

### ISSUE THREAD

**Issue by GuillaumeGomez** [GuillaumeGomez/tuto-rust-fr#20]
Certains mots ont été traduits de l'anglais, il serait bien de donner leur traduction en anglais pour éviter que les gens ne soient perdus s'ils cherchent quelque chose.

**Comment by Songbird0** [comment]
Hello,

Cette issue date un peu, est-ce que tu as encore en tête les termes qui n'ont pas leur équivalent en Anglais ?

**Comment by GuillaumeGomez** [comment]
C'était quelqu'un d'autre qui me l'avait remonté. À l'époque je me suis dit que je le ferai dès que j'aurais un peu de temps mais on sait tous comment ça a fini... Du coup je n'ai aucune idée de quels termes il s'agit...

**Comment by Songbird0** [comment]
Mince. Je jetterai un œil demain au document, voir s'il y a des termes français qui seraient difficilement traduisible vers l'anglais. Enfin, si ça t'intéresse toujours.

**Comment by GuillaumeGomez** [comment]
Toute amélioration est bonne à prendre !
