### ISSUE TITLE
Ajouter un chapitre sur "jouer avec les iterators/str"

### ISSUE THREAD

**Issue by GuillaumeGomez** [GuillaumeGomez/tuto-rust-fr#22]
Genre avec map/collect/zip.

**Comment by Songbird0** [comment]
Hello,

La doc de la std a déjà pas mal d'exemples à ce sujet. Sachant que l'issue date un peu, qu'est-ce que tu voudrais ajouter qui n'existe pas dans la doc officielle ?

**Comment by GuillaumeGomez** [comment]
Tant qu'à faire ce serait pas mal. J'avais cet [article](https://blog.guillaume-gomez.fr/articles/2017-03-09+Little+tour+of+multiple+iterators+implementation+in+Rust) il y a un moment, ça vaudrait peut-être la peine que je l'inclus dans le tuto directement ?

**Comment by Songbird0** [comment]
Ah bah oui clairement, il ne manque plus que la traduction.

**Comment by GuillaumeGomez** [comment]
Si t'as le temps et la motivation, n'hésite pas à le faire. Ce serait fortement apprécié. :)

**Comment by Songbird0** [comment]
C'est pas impossible. Par contre, je pense qu'on devrait faire de cet article le treizième chapitre de la section *Spécificités de Rust*, ou encore à la rigueur le placer juste après avoir abordé les notions d'ownership et de lifetime. Qu'est-ce que tu en penses ?

**Comment by GuillaumeGomez** [comment]
Il y a besoin de connaissances sur les boucles et les lifetimes pour comprendre ce chapitre. À part ça c'est tout donc du moment que ça remplit ces 2 conditions, ça me va !

**Comment by Songbird0** [comment]
La PR est merge, je ferme !
