### ISSUE TITLE
Ajout d'un autre éditeur de Rust online

### ISSUE THREAD

**Issue by mothsART** [GuillaumeGomez/tuto-rust-fr#25]
Dans la section "Mise en place des outils", il serait sans doute judicieux de parler de http://www.tutorialspoint.com/compile_rust_online.php

Plusieurs avantages par rapport à https://play.rust-lang.org/ :
- édition sur plusieurs fichiers (+ download/upload d'un projet complet)
- un shell sh de dispo

**Comment by GuillaumeGomez** [comment]
Je connaissais pas. Tu veux l'ajouter toi-même dans le tuto ? :)
