### ISSUE TITLE
Placer le tutoriel en ordre

### ISSUE THREAD

**Issue by Coder206** [GuillaumeGomez/tuto-rust-fr#29]
J'ai remarqué que le dossier `src` contient des documents mais elles ne sont pas en ordre. Par exemple: 1, 10, 12 ... 19, 2, 20 ...

Il serait mieux de renommer les filières 00, 01, 02 ... 09, 10 ...

**Comment by GuillaumeGomez** [comment]
Je ne vois pas vraiment l'intérêt de le changer. Le nombre de fichier est relativement restreint donc ça n'est pas gênant de mon point de vue.

**Comment by Coder206** [comment]
Je comprends!
