### ISSUE TITLE
__Send__ and __send__ c'est la même chose

### ISSUE THREAD

**Issue by sbechet** [GuillaumeGomez/tuto-rust-fr#46]
[sSend.diff.txt](https://github.com/GuillaumeGomez/tuto-rust-fr/files/2073686/sSend.diff.txt)

**Comment by GuillaumeGomez** [comment]
Tu préfères pas ouvrir une pull request plutôt ? Si j'applique ton patch moi-même, tu n'en auras pas l'ownership et ça m'embête un peu...

**Comment by sbechet** [comment]
En pull request.
