### ISSUE TITLE
Some()

### ISSUE THREAD

**Issue by sbechet** [GuillaumeGomez/tuto-rust-fr#48]
Penser à préciser l'usage de Some() afin d'avoir une lecture fluide.

**Comment by GuillaumeGomez** [comment]
Il faut que je refasse une passe sur le tuto de toute façon. Je l'ai écrit en 2015 donc pas mal de choses méritent d'être mise à jour ou améliorée.

**Comment by Songbird0** [comment]
Je me permet de déterrer cette issue pour savoir ce que @sbechet entendait par:

> Penser à préciser l'usage de Some() afin d'avoir une lecture fluide.

Dans quelle(s) partie(s) du livre il faudrait apporter des précisions ?

Merci d'avance.

**Comment by GuillaumeGomez** [comment]
Peut-être quand je parle des newtypes ? Je ne sais pas trop exactement parce que je ne vois pas vraiment ça comme une partie à part entière...

**Comment by sbechet** [comment]
Si j'ai bien compris, ce tutorial a pour objectif les débutants.

Dans une lecture "one shot" du tuto, il est fait l'usage de `Some()` et `None` sans en expliquer l'origine.

J'aurai du préciser qu'il faudrait peut-être l'introduire `Enum std::option::Option` au début de `1_6.md` juste avant le chapitre sur `if let` ?

**Comment by Songbird0** [comment]
> Dans une lecture "one shot" du tuto, il est fait l'usage de Some() et None sans en expliquer l'origine.

Oui je viens de voir, d'autant plus que lorsqu'on ne connaît pas le langage un `match Some(x)` peut paraître bien magique. J'ai ouvert la #57 pour garder en tête ce qu'il y a à noter. Merci !

**Comment by sbechet** [comment]
Si tout le monde est d'accord, je ferme cette issue cf. #57
