### ISSUE TITLE
Créer une section introduisant l'enum `std::option::Option`

### ISSUE THREAD

**Issue by Songbird0** [GuillaumeGomez/tuto-rust-fr#57]
Issue liée à #48 

Pour l'introduction, je pense qu'il serait suffisant d'aborder le concept de ressource présente/non-présente contrairement à d'autres langages où la notion de pointeur nul est acceptée, puis finir par la déstructuration des variantes (ce qui complèterait le chapitre lié au pattern matching).

Par contre si la section est placée *avant* le chapitre abordant if/while let, il va falloir réorganiser les autres sections (changer leur place/numéro).

**Comment by GuillaumeGomez** [comment]
J'ai ajouté un chapitre sur la gestion des erreurs en Rust. Il y aussi le chapitre sur les enums. Je pense que cette issue a été résolue.
