### ISSUE TITLE
Réorganiser les exemples de structures

### ISSUE THREAD

**Issue by dkurzaj** [GuillaumeGomez/tuto-rust-fr#59]
Dans le chapitre sur les structures (II.2 https://blog.guillaume-gomez.fr/Rust/2/2), les structures sont listées selon un certain ordre, puis le premier exemple (déclarations) les présente dans un ordre différent, et le second exemple (instanciations) les présente dans un ordre encore différent.

Je trouve que cela rends la lecture moins compréhensible au premier regard que si l'ordre était toujours le même.

**Comment by GuillaumeGomez** [comment]
En effet. Motivé pour faire le changement ? Je ferai la modif' ce w-e sinon (si je n'oublie pas...).

**Comment by GuillaumeGomez** [comment]
Fixed by #60.
