### ISSUE TITLE
Exemple d'ownership qui compile désormais

### ISSUE THREAD

**Issue by dkurzaj** [GuillaumeGomez/tuto-rust-fr#61]
L'avant dernier bloc d'exemple (en bas de la page) de II.5 (https://blog.guillaume-gomez.fr/Rust/2/5) sur l'ownership est indiqué comme ne compilant pas, or, il semble que désormais le compilateur n'ait pas de problème avec ce code :
```rust
fn main() {
    let reference: &i32;
    let x = 5;
    reference = &x;

    println!("{}", reference);
}
```
Il faudrait donc sûrement retravailler ce passage qui proposait un version corrigée du code juste en-dessous.

**Comment by GuillaumeGomez** [comment]
Je pense que je vais garder le code en précisant bien qu'il fonctionne maintenant. Ou alors trouver un équivalent mais là j'ai du mal à voir...

Merci pour la remontée en tout cas !
