### ISSUE TITLE
[Chapitre 1-Module 9] Expressions : Problème compilation

### ISSUE THREAD

**Issue by grouville** [GuillaumeGomez/tuto-rust-fr#73]
Bonjour,

Merci tout d'abord pour cette excellente documentation, elle est limpide ! 😄 

L'objet de cet issue est à propos d'une erreur de typo amenant à une erreur de compilation dans le Chapitre 1, Module 9 (Expressions) :

```
let var: i32 = if true {
    1u32;
} else {
    2u32;
};
```

Après avoir `run`, on voit que le compilateur bug sur le cast d'`u32` vers `i32`

**Comment by GuillaumeGomez** [comment]
En effet, merci beaucoup pour la remontée !
