### ISSUE TITLE
Jeu du plus ou moins - Solution: rand::thread_rng().gen_range(1, 101);

### ISSUE THREAD

**Issue by henri228** [GuillaumeGomez/tuto-rust-fr#77]
Bonjour,

Je suis en train de suivre votre tuto Rust, qui est super bien fait, merci pour cela ! 

Dans le chapitre "Jeu du Plus ou Moins", dans votre solution pour générer un nombre aléatoire entre 1 et 100, j'obtiens une erreur.

`let nombre_aleatoire = rand::thread_rng().gen_range(1, 101);`

Dans la doc de rand, il semble qu'il faille utiliser: 

`let nombre_aleatoire = rand::thread_rng().gen_range(1..101);`

Donc `..` entre les deux valeurs et non `,` .

En espérant que cela soit utile pour les autres.

Cheers

**Comment by GuillaumeGomez** [comment]
Ah je vois que l'API a évolué depuis le temps. Je vais mettre  jour, merci pour le retour !

**Comment by henri228** [comment]
Excellent ! :-)
Pour info, j'ai également eu une erreur en ajoutant la dépendance: 

```
[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"

```
Lorsque je lance cargo run , le build failed:

error: failed to run custom build command for glib-sys v0.10.0 (https://github.com/gtk-rs/sys#5f35e26c)``

**Comment by GuillaumeGomez** [comment]
C'est tout simplement parce qu'il faut avoir les libs d'installées (gtk and co). Sur windows c'est un peu le bordel, sur linux juste "apt install" ou équivalent et c'est réglé. Cependant je vais ajouter une précision comme quoi il faut que ça soit installé (et aussi mettre un lien vers le projet, tant qu'à faire...).

**Comment by henri228** [comment]
Excellent, merci pour ta réactivité Guillaume !

**Comment by GuillaumeGomez** [comment]
Pas de soucis, merci beaucoup pour les retours!

**Comment by GuillaumeGomez** [comment]
Le site a été mis à jour. Encore merci !
